{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plnmodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PLNmodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PLNmodels/PLNmodels_{{ version }}.tar.gz
  sha256: b6696b0616d9555950d7e788cf9298d5d6f7340f18256b92cb89fa84070e318f

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-corrplot
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-glassofast
    - r-gridextra
    - r-igraph
    - r-magrittr
    - r-mass
    - r-matrix
    - r-nloptr
    - r-purrr
    - r-r6
    - r-rcpp
    - r-rcpparmadillo
    - r-rlang
    - r-tidyr
    - r-torch
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-corrplot
    - r-dplyr
    - r-future
    - r-future.apply
    - r-ggplot2
    - r-glassofast
    - r-gridextra
    - r-igraph
    - r-magrittr
    - r-mass
    - r-matrix
    - r-nloptr
    - r-purrr
    - r-r6
    - r-rcpp
    - r-rcpparmadillo
    - r-rlang
    - r-tidyr
    - r-torch

test:
  commands:
    - $R -e "library('PLNmodels')"           # [not win]
    - "\"%R%\" -e \"library('PLNmodels')\""  # [win]

about:
  home: https://pln-team.github.io/PLNmodels/
  dev_url: https://github.com/pln-team/PLNmodels/
  doc_url: https://pln-team.github.io/PLNmodels/reference/index.html
  license: GPL-3.0-or-later
  summary: The Poisson-lognormal model and variants can be used for a variety of multivariate problems when count data are at play, including principal component analysis for count data (Chiquet, Mariadassou and Robin, 2018 <doi:10.1214/18-AOAS1177>), discriminant analysis and network inference (Chiquet, Mariadassou and
    Robin, 2018 <http://proceedings.mlr.press/v97/chiquet19a.html>). Implements variational algorithms to fit such models accompanied with a set of functions for visualization and diagnostic.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jchiquet
    - cpauvert
